export const excoData = [
  {
    image: '',
    name: 'Emuesiri Omoware',
    position: 'Chairman',
    Occupation: 'Business Man',
    dob: 1988,
  },
  {
    image: '',
    name: 'Lucky Okhilua',
    position: 'Vice-President',
    Occupation: 'Cinematographer',
    dob: 1988,
  },
  {
    image: '',
    name: 'Emadomi Koko Emmanuel',
    position: 'Secretary',
    Occupation: 'Artiste',
    dob: 1988,
  },
  {
    image: '',
    name: 'Oghenetobore Gift Boye',
    position: 'Finiancial Officer',
    Occupation: 'Business Man',
    dob: 1988,
  },
  {
    image: '',
    name: 'Onyeloni Juliet Idika',
    position: 'Director of Socials',
    Occupation: 'Entrepreneur',
    dob: 1988,
  },
  {
    image: '',
    name: 'Afolabi Olatunde',
    position: 'Chief Security Officer',
    Occupation: 'Naval Officer',
    dob: 1988,
  },
  {
    image: '',
    name: 'Momodu Dauda',
    position: 'Director of Cybersecurity/Technology',
    Occupation: 'Business Man',
    dob: 1988,
  },
  {
    image: '',
    name: 'Emojevwe Paul',
    position: 'Deputy Director of Cybersecurity',
    Occupation: 'Seaman',
    dob: 1988,
  },
  {
    image: '',
    name: 'Afamefuna Ezeiruaku',
    position: 'Director of Medicals',
    Occupation: 'Medical Doctor',
    dob: 1988,
  },
  {
    image: '',
    name: 'Ajemutabe Faith',
    position: 'Public Relation Officer',
    Occupation: 'Entrepreneur',
    dob: 1988,
  },
  {
    image: '',
    name: 'Elliot Asamabiri',
    position: 'Disciplinary Officer',
    Occupation: 'Politician',
    dob: 1988,
  },
  {
    image: '',
    name: 'Agherarior Emmanuel',
    position: 'Chest Bearer',
    Occupation: 'Barrister',
    dob: 1988,
  },
];